export default [
  {
    url: 'https://media.architecturaldigest.com/photos/5d76c7266c05d1000ae1dff8/master/w_1867,h_2000,c_limit/GettyImages-664617586.jpg',
    name: 'Wildstone Infra Hotel',
    address: '2715 Ash Dr. San Jose, South Dakota',
    type: 'commercial',
  },
  {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/HK-2IFC-sj_cropped.jpg/640px-HK-2IFC-sj_cropped.jpg',
    name: 'Wish Stone Building',
    address: '2972 Westheimer Rd. Santa Ana, Illinois',
    type: 'commercial',
  },
  {
    url: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTB8fGhvdXNlfGVufDB8fDB8fA%3D%3D&w=1000&q=80',
    name: 'Mr. Parkinston’s House',
    address: '3517 W. Gray St. Utica, Pennsylvania',
    type: 'residental',
  },
  {
    url: 'https://i.natgeofe.com/k/36ab45c4-e88c-4cc8-a71f-5103a0fc008c/a-8-skyscrapers-turning-torso_2x3.jpg',
    name: 'Oregano Height',
    address: '2464 Royal Ln. Mesa, New Jersey',
    type: 'commercial',
  },
  {
    url: 'https://static.dezeen.com/uploads/2017/03/the-mit-media-lab-worlds-best-university-architecture-20-qs-survey-ranking-flickr-knight-foundation_dezeen_hero.jpg',
    name: 'The University of Architecture',
    address: '2207 Piedmont Ave Berkeley, California',
    type: 'other',
  },
  {
    url: 'https://iea.imgix.net/baf1e3a9-a015-4917-8206-021234e74453/matthew-hamilton-Ru3Ap8TNcsk-unsplash.jpg?auto=compress%2Cformat&fit=min&q=80&rect=0%2C0%2C5472%2C3648&w=1800&h=1200&fit=crop&fm=jpg&q=70&auto=format',
    name: 'Old Sity Hall',
    address: 'Buildings, IEA, Paris',
    type: 'other',
  },
  {
    url: 'https://assets.nrdc.org/sites/default/files/styles/full_content--retina/public/media-uploads/enrpsd6_flickr_christian-schnettelker_cc_2400.jpg?itok=oZS41wmi',
    name: 'Buildings in China',
    address: 'China',
    type: 'other',
  },
  {
    url: 'https://i0.wp.com/theconstructor.org/wp-content/uploads/2014/10/lodge-house.jpg?resize=450%2C268&ssl=1',
    name: 'Rooming House',
    address: '1509 7th Ave Austin, Minnesota',
    type: 'residental',
  },
  {
    url: 'https://i0.wp.com/theconstructor.org/wp-content/uploads/2014/10/private-dwelling.jpg?resize=450%2C242&ssl=1',
    name: 'Private dwelling',
    address: '429 N Main St Keyser, West Virginia',
    type: 'residental',
  },
  {
    url: 'https://ca.gcpat.com/sites/default/files/las_vegas_strip_standard.jpg',
    name: 'CityCenter Las Vegas',
    address: 'S Las Vegas Blvd, Las Vegas',
    type: 'commercial',
  },
  {
    url: 'https://ca.gcpat.com/sites/default/files/singapore_standard.jpg',
    name: 'The ION Orchard',
    address: 'Singapore ',
    type: 'commercial',
  },
  {
    url: 'https://ca.gcpat.com/sites/default/files/q1tower_goldcoast%2Caustralia_adva_standard.jpg',
    name: 'The Q1',
    address: 'Queensland, Australia',
    type: 'commercial',
  },
  {
    url: 'https://ca.gcpat.com/sites/default/files/2017-06/newcastle-hospital-waterproofing-header.jpg',
    name: 'Newcastle Hospitals',
    address: 'Newcastle',
    type: 'other',
  },
  {
    url: 'https://ca.gcpat.com/sites/default/files/georgia_aquarium_header.jpg',
    name: 'The Georgia Aquarium',
    address: '3824 221st Hwy Uvalda, Georgia',
    type: 'other',
  },
  {
    url: 'https://assets-news.housing.com/news/wp-content/uploads/2019/03/25173457/R-D.jpg',
    name: 'Office',
    address: '74 2nd Ave Ilion, New York',
    type: 'commercial',
  },
  {
    url: 'https://assets-news.housing.com/news/wp-content/uploads/2019/03/25172447/data-centre.jpg',
    name: 'Data hosting centre',
    address: '247 Arapahoe Rd Winter Park, Colorado',
    type: 'other',
  },
  {
    url: 'https://www.webuyhomeswinnipeg.com/uploads/1/3/2/7/132794511/sell-my-home-for-cash-winnipeg_orig.png',
    name: 'Mr. Smith’s House',
    address: '34244 Tot Polk Rd Pearl River, Louisiana',
    type: 'residental',
  },
];
